### ISSUE TITLE
Export to CSV is not working 

### ISSUE THREAD

**Issue by Stingray91** [AntlerVC/firetable#1434] opened 2023-10-12 15:50 UTC
The export to CSV for all fields is not working. It seems that the larger tables just don't export (exports fine for JSON). The popup that says that the download will begin soon pops up but nothing downloads.

**Comment by harinij** [comment] 2023-10-16 23:06
@Stingray91 is the number of rows in the table >10K?

**Comment by Stingray91** [comment] 2023-10-17 11:00
Yes there are no more than 500 in there
________________________________

**Comment by harinij** [comment] 2023-12-18 09:33
Hi @Stingray91 - we weren't able to reproduce this. potentially it could be related to the data seen in the table itself? If you can try for smaller number of columns in the export does it work or narrow it down? 

Moving this to discussion as it seems to be related to specific dataset

**Closed as completed** 2023-12-18 09:33 UTC
